media:
  input: public
  output: /

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/post
    filename: "{year}-{month}-{day}-{primary}/index.mdx"
    view:
      fields: [title, draft, publishDate]
      layout: tree
      node:
        filename: index.mdx
    fields:
      - name: title
        label: Title
        type: string
        required: true
        pattern:
          regex: '^.{1,60}$'
          message: 'Title must be at most 60 characters.'
      - name: description
        label: Description
        type: string
        required: true
        multiline: true
        hint: 50–160 characters recommended
        pattern:
          regex: '^[\s\S]{50,160}$'
          message: 'Description must be between 50 and 160 characters.'
      - name: publishDate
        label: Publish date
        type: date
        required: true
        pattern:
          regex: '^\\d{4}-\\d{2}-\\d{2}$'
          message: 'Use YYYY-MM-DD (e.g., 2025-08-31).'
        hint: 'Format: YYYY-MM-DD'
      - name: updatedDate
        label: Updated date
        type: date
        required: false
        pattern:
          regex: '^\\d{4}-\\d{2}-\\d{2}$'
          message: 'Use YYYY-MM-DD (e.g., 2025-08-31).'
        hint: 'Format: YYYY-MM-DD'
      - name: coverImage
        label: Cover image
        type: object
        required: false
        fields:
          - name: src
            label: Image (local or public)
            type: image
            # Default to colocating next to the post
            options:
              input: src/content/post
              output: .
            hint: 'Prefer local (./cover.jpg). For public image, switch picker path to public/images and choose a /images/... path.'
          - name: alt
            label: Alt text
            type: string
            required: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: tags
        label: Tags
        type: string
        list: true
      - name: ogImage
        label: Open Graph Image (URL or public path)
        type: string
        required: false
      - name: body
        label: Body
        type: rich-text
        options:
          # Default colocated uploads
          input: src/content/post
          output: .
          # Tip: To use public assets, change folder to public/images in the picker and the editor will insert /images/... paths.
